<?php
@session_start();

//这里是注册码，替换成你购买的即可。
$sLicense = "2:21882:4:2:1::114.215.105.187:02b7b7bd1352aabe292058c87a3dc8ab";

$sUsername = "admin";
$sPassword = "adminasdfqwerqwerqwerwerqwe";
if(isset($_SESSION['uid']) === false || isset($_SESSION['token']) === false){exit("please login");}

$myupload="../../uploads/" . $_SESSION['uid'] ."/" . $_SESSION['token'] ."/";

//修正部份计算机 DOCUMENT_ROOT 无值的问题
if(empty($_SERVER['DOCUMENT_ROOT']) && !empty($_SERVER['SCRIPT_FILENAME'])) {
if(PATH_SEPARATOR==':') $_SERVER['DOCUMENT_ROOT'] = str_replace( '\\', '/', substr($_SERVER['SCRIPT_FILENAME'], 0, 0 - strlen($_SERVER['PHP_SELF'])));
else $_SERVER['DOCUMENT_ROOT'] = substr($_SERVER['SCRIPT_FILENAME'], 0, 0 - strlen($_SERVER['PHP_SELF']));
}else if(empty($_SERVER['DOCUMENT_ROOT']) && !empty($_SERVER['PATH_TRANSLATED'])) {
    if(PATH_SEPARATOR==':') $_SERVER['DOCUMENT_ROOT'] = str_replace( '\\', '/', substr(str_replace('\\\\', '\\', $_SERVER['PATH_TRANSLATED']), 0, 0 - strlen($_SERVER['PHP_SELF'])));
    else $_SERVER['DOCUMENT_ROOT'] = substr(str_replace('\\\\', '\\', $_SERVER['PATH_TRANSLATED']), 0, 0 - strlen($_SERVER['PHP_SELF']));
}

if (!file_exists($_SERVER['DOCUMENT_ROOT'].'/uploads')||!is_dir($_SERVER['DOCUMENT_ROOT'].'/uploads')){
	@mkdir($_SERVER['DOCUMENT_ROOT'].'/uploads',0777);
}
$firstLetterDir=$_SERVER['DOCUMENT_ROOT'].'/uploads/'.$_SESSION['uid'];
if (!file_exists($firstLetterDir)||!is_dir($firstLetterDir)){
	@mkdir($firstLetterDir,0777);
}
if (!file_exists($firstLetterDir.'/'.$_SESSION['token'])||!is_dir($firstLetterDir.'/'.$_SESSION['token'])){
	@mkdir($firstLetterDir.'/'.$_SESSION['token'],0777);
}
//echo $myupload;die();

$aStyle[1] = "jhbar||||||office2003|||".$myupload."|||650|||350|||rar|zip|pdf|doc|xls|ppt|chm|hlp|||swf|||gif|jpg|jpeg|bmp|png|||rm|flv|wmv|asf|mov|mpg|mpeg|avi|mp3|wav|mid|midi|ra|wma|||gif|jpg|bmp|png|||10240|||1024|||512|||10240|||512|||1|||1|||EDIT|||1|||0||||||||||||1|||0|||650px宽度界面下的标准工具栏按钮|||1|||zh-cn|||0|||300|||120|||0|||版权所有...|||000000|||12|||宋体||||||1|||jpg|jpeg|||512|||FFFFFF|||1|||1|||gif|jpg|bmp|wmz|png|||512|||100|||1|||73|||17|||5|||5|||0|||100|||100|||1|||5|||5|||88|||31|||1|||0|||1|||1|||1|||1|||1|||0|||0|||0|||||||||1|||{page}|||0|||2000|||1|||0||||||0|||200|||1|||2|||1|||1|||1|||0||||||0|||||||||||||||||||||1|||||||||300|||1||||||||||||||||||1|||";
$aStyle[2] = "standard600||||||office2003|||".$myupload."|||600|||350|||rar|zip|pdf|doc|xls|ppt|chm|hlp|||swf|||gif|jpg|jpeg|bmp|png|||rm|flv|wmv|asf|mov|mpg|mpeg|avi|mp3|wav|mid|midi|ra|wma|||gif|jpg|bmp|png|||500|||100|||100|||100|||100|||1|||1|||EDIT|||1|||0||||||||||||1|||0|||600px宽度界面下的标准工具栏按钮(推荐)|||1|||zh-cn|||0|||300|||120|||0|||版权所有...|||000000|||12|||宋体||||||0|||jpg|jpeg|||100|||FFFFFF|||1|||1|||gif|jpg|bmp|wmz|png|||100|||100|||1|||66|||17|||5|||5|||0|||100|||100|||1|||5|||5|||88|||31|||1|||0|||1|||1|||1|||1|||1|||0|||0|||0|||||||||1|||{page}|||0|||2000|||1|||0||||||0|||200|||1|||2|||1|||1|||1|||0||||||0|||||||||||||||||||||1|||||||||300|||1||||||||||||||||||1|||";
$aStyle[3] = "standard550||||||office2003|||".$myupload."|||550|||350|||rar|zip|pdf|doc|xls|ppt|chm|hlp|||swf|||gif|jpg|jpeg|bmp|png|||rm|flv|wmv|asf|mov|mpg|mpeg|avi|mp3|wav|mid|midi|ra|wma|||gif|jpg|bmp|png|||500|||100|||100|||100|||100|||1|||1|||EDIT|||1|||0||||||||||||1|||0|||550px宽度界面下的标准工具栏按钮(推荐)|||1|||zh-cn|||0|||300|||120|||0|||版权所有...|||000000|||12|||宋体||||||0|||jpg|jpeg|||100|||FFFFFF|||1|||1|||gif|jpg|bmp|wmz|png|||100|||100|||1|||66|||17|||5|||5|||0|||100|||100|||1|||5|||5|||88|||31|||1|||0|||1|||1|||1|||1|||1|||0|||0|||0|||||||||1|||{page}|||0|||2000|||1|||0||||||0|||200|||1|||2|||1|||1|||1|||0||||||0|||||||||||||||||||||1|||||||||300|||1||||||||||||||||||1|||";
$aStyle[4] = "standard500||||||office2003|||".$myupload."|||500|||350|||rar|zip|pdf|doc|xls|ppt|chm|hlp|||swf|||gif|jpg|jpeg|bmp|png|||rm|flv|wmv|asf|mov|mpg|mpeg|avi|mp3|wav|mid|midi|ra|wma|||gif|jpg|bmp|png|||500|||100|||100|||100|||100|||1|||1|||EDIT|||1|||0||||||||||||1|||0|||500px宽度界面下的标准工具栏按钮|||1|||zh-cn|||0|||300|||120|||0|||版权所有...|||000000|||12|||宋体||||||0|||jpg|jpeg|||100|||FFFFFF|||1|||1|||gif|jpg|bmp|wmz|png|||100|||100|||1|||66|||17|||5|||5|||0|||100|||100|||1|||5|||5|||88|||31|||1|||0|||1|||1|||1|||1|||1|||0|||0|||0|||||||||1|||{page}|||0|||2000|||1|||0||||||0|||200|||1|||2|||1|||1|||1|||0||||||0|||||||||||||||||||||1|||||||||300|||1||||||||||||||||||1|||";
$aStyle[5] = "full650||||||office2003|||".$myupload."|||650|||400|||rar|zip|pdf|doc|xls|ppt|chm|hlp|||swf|||gif|jpg|jpeg|bmp|png|||rm|flv|wmv|asf|mov|mpg|mpeg|avi|mp3|wav|mid|midi|ra|wma|||gif|jpg|bmp|png|||500|||100|||100|||100|||100|||1|||1|||EDIT|||1|||0||||||||||||1|||0|||650px宽度界面下的所有功能按钮展示,功能按钮有可能重复|||1|||zh-cn|||0|||300|||120|||0|||版权所有...|||000000|||12|||宋体||||||0|||jpg|jpeg|||100|||FFFFFF|||1|||1|||gif|jpg|bmp|wmz|png|||100|||100|||1|||73|||17|||5|||5|||0|||100|||100|||1|||5|||5|||88|||31|||1|||0|||1|||1|||1|||1|||1|||0|||0|||0|||||||||1|||{page}|||0|||2000|||1|||0||||||0|||200|||1|||2|||1|||1|||1|||0||||||0|||||||||||||||||||||1|||||||||300|||1||||||||||||||||||1|||";
$aStyle[6] = "mini500||||||office2003|||".$myupload."|||500|||300|||rar|zip|pdf|doc|xls|ppt|chm|hlp|||swf|||gif|jpg|jpeg|bmp|png|||rm|flv|wmv|asf|mov|mpg|mpeg|avi|mp3|wav|mid|midi|ra|wma|||gif|jpg|bmp|png|||500|||100|||100|||100|||100|||1|||1|||EDIT|||1|||0||||||||||||1|||0|||500px宽度界面下的最简工具栏按钮,适合于邮件系统留言系统等只需最简单功能的应用|||1|||zh-cn|||0|||300|||120|||0|||版权所有...|||000000|||12|||宋体||||||0|||jpg|jpeg|||100|||FFFFFF|||1|||1|||gif|jpg|bmp|wmz|png|||100|||100|||1|||66|||17|||5|||5|||0|||100|||100|||1|||5|||5|||88|||31|||1|||0|||1|||1|||1|||1|||1|||0|||0|||0|||||||||1|||{page}|||0|||2000|||1|||0||||||0|||200|||1|||2|||1|||1|||1|||0||||||0|||||||||||||||||||||1|||||||||300|||1||||||||||||||||||1|||";
$aStyle[7] = "menu400||||||office2003|||".$myupload."|||400|||250|||rar|zip|pdf|doc|xls|ppt|chm|hlp|||swf|||gif|jpg|jpeg|bmp|png|||rm|flv|wmv|asf|mov|mpg|mpeg|avi|mp3|wav|mid|midi|ra|wma|||gif|jpg|bmp|png|||500|||100|||100|||100|||100|||1|||1|||EDIT|||1|||0||||||||||||1|||0|||400px宽度,工具栏全部菜单按钮,所有功能,占位小|||1|||zh-cn|||0|||300|||120|||0|||版权所有...|||FF0000|||12|||宋体||||||0|||jpg|jpeg|||100|||FFFFFF|||1|||1|||gif|jpg|bmp|wmz|png|||100|||100|||1|||73|||17|||5|||5|||0|||100|||100|||1|||5|||5|||88|||31|||1|||0|||1|||1|||1|||1|||1|||0|||0|||0|||||||||1|||{page}|||0|||2000|||1|||0||||||0|||200|||1|||2|||1|||1|||1|||0||||||0|||||||||||||||||||||1|||||||||300|||1||||||||||||||||||1|||";
$aStyle[8] = "coolblue||||||office2003|||".$myupload."|||550|||350|||rar|zip|pdf|doc|xls|ppt|chm|hlp|||swf|||gif|jpg|jpeg|bmp|png|||rm|flv|wmv|asf|mov|mpg|mpeg|avi|mp3|wav|mid|midi|ra|wma|||gif|jpg|bmp|png|||500|||100|||100|||100|||100|||1|||1|||EDIT|||1|||0||||||||||||1|||0|||V4.x版保留,standard550标配,office2003皮肤|||1|||zh-cn|||0|||300|||120|||0|||版权所有...|||000000|||12|||宋体||||||0|||jpg|jpeg|||100|||FFFFFF|||1|||1|||gif|jpg|bmp|wmz|png|||100|||100|||1|||66|||17|||5|||5|||0|||100|||100|||1|||5|||5|||88|||31|||1|||0|||1|||1|||1|||1|||1|||0|||0|||0|||||||||1|||{page}|||0|||2000|||1|||0||||||0|||200|||1|||2|||1|||1|||1|||0||||||0|||||||||||||||||||||1|||||||||300|||1||||||||||||||||||1|||";
$aStyle[9] = "gray||||||office2000|||".$myupload."|||550|||350|||rar|zip|pdf|doc|xls|ppt|chm|hlp|||swf|||gif|jpg|jpeg|bmp|png|||rm|flv|wmv|asf|mov|mpg|mpeg|avi|mp3|wav|mid|midi|ra|wma|||gif|jpg|bmp|png|||500|||100|||100|||100|||100|||1|||1|||EDIT|||1|||0||||||||||||1|||0|||V4.x版保留,standard550标配,office2000皮肤|||1|||zh-cn|||0|||300|||120|||0|||版权所有...|||000000|||12|||宋体||||||0|||jpg|jpeg|||100|||FFFFFF|||1|||1|||gif|jpg|bmp|wmz|png|||100|||100|||1|||66|||17|||5|||5|||0|||100|||100|||1|||5|||5|||88|||31|||1|||0|||1|||1|||1|||1|||1|||0|||0|||0|||||||||1|||{page}|||0|||2000|||1|||0||||||0|||200|||1|||2|||1|||1|||1|||0||||||0|||||||||||||||||||||1|||||||||300|||1||||||||||||||||||1|||";
$aStyle[10] = "light||||||light1|||".$myupload."|||550|||350|||rar|zip|pdf|doc|xls|ppt|chm|hlp|||swf|||gif|jpg|jpeg|bmp|png|||rm|flv|wmv|asf|mov|mpg|mpeg|avi|mp3|wav|mid|midi|ra|wma|||gif|jpg|bmp|png|||500|||100|||100|||100|||100|||1|||1|||EDIT|||1|||0||||||||||||1|||0|||V4.x版保留,standard550标配,light1皮肤|||1|||zh-cn|||0|||300|||120|||0|||版权所有...|||000000|||12|||宋体||||||0|||jpg|jpeg|||100|||FFFFFF|||1|||1|||gif|jpg|bmp|wmz|png|||100|||100|||1|||66|||17|||5|||5|||0|||100|||100|||1|||5|||5|||88|||31|||1|||0|||1|||1|||1|||1|||1|||0|||0|||0|||||||||1|||{page}|||0|||2000|||1|||0||||||0|||200|||1|||2|||1|||1|||1|||0||||||0|||||||||||||||||||||1|||||||||300|||1||||||||||||||||||1|||";
$aStyle[11] = "blue||||||blue2|||".$myupload."|||550|||350|||rar|zip|pdf|doc|xls|ppt|chm|hlp|||swf|||gif|jpg|jpeg|bmp|png|||rm|flv|wmv|asf|mov|mpg|mpeg|avi|mp3|wav|mid|midi|ra|wma|||gif|jpg|bmp|png|||500|||100|||100|||100|||100|||1|||1|||EDIT|||1|||0||||||||||||1|||0|||V4.x版保留,standard550标配,blue2皮肤|||1|||zh-cn|||0|||300|||120|||0|||版权所有...|||000000|||12|||宋体||||||0|||jpg|jpeg|||100|||FFFFFF|||1|||1|||gif|jpg|bmp|wmz|png|||100|||100|||1|||66|||17|||5|||5|||0|||100|||100|||1|||5|||5|||88|||31|||1|||0|||1|||1|||1|||1|||1|||0|||0|||0|||||||||1|||{page}|||0|||2000|||1|||0||||||0|||200|||1|||2|||1|||1|||1|||0||||||0|||||||||||||||||||||1|||||||||300|||1||||||||||||||||||1|||";
$aStyle[12] = "green||||||green1|||".$myupload."|||550|||350|||rar|zip|pdf|doc|xls|ppt|chm|hlp|||swf|||gif|jpg|jpeg|bmp|png|||rm|flv|wmv|asf|mov|mpg|mpeg|avi|mp3|wav|mid|midi|ra|wma|||gif|jpg|bmp|png|||500|||100|||100|||100|||100|||1|||1|||EDIT|||1|||0||||||||||||1|||0|||V4.x版保留,standard550标配,green1皮肤|||1|||zh-cn|||0|||300|||120|||0|||版权所有...|||000000|||12|||宋体||||||0|||jpg|jpeg|||100|||FFFFFF|||1|||1|||gif|jpg|bmp|wmz|png|||100|||100|||1|||66|||17|||5|||5|||0|||100|||100|||1|||5|||5|||88|||31|||1|||0|||1|||1|||1|||1|||1|||0|||0|||0|||||||||1|||{page}|||0|||2000|||1|||0||||||0|||200|||1|||2|||1|||1|||1|||0||||||0|||||||||||||||||||||1|||||||||300|||1||||||||||||||||||1|||";
$aStyle[13] = "red||||||red1|||".$myupload."|||550|||350|||rar|zip|pdf|doc|xls|ppt|chm|hlp|||swf|||gif|jpg|jpeg|bmp|png|||rm|flv|wmv|asf|mov|mpg|mpeg|avi|mp3|wav|mid|midi|ra|wma|||gif|jpg|bmp|png|||500|||100|||100|||100|||100|||1|||1|||EDIT|||1|||0||||||||||||1|||0|||V4.x版保留,standard550标配,red1皮肤|||1|||zh-cn|||0|||300|||120|||0|||版权所有...|||000000|||12|||宋体||||||0|||jpg|jpeg|||100|||FFFFFF|||1|||1|||gif|jpg|bmp|wmz|png|||100|||100|||1|||66|||17|||5|||5|||0|||100|||100|||1|||5|||5|||88|||31|||1|||0|||1|||1|||1|||1|||1|||0|||0|||0|||||||||1|||{page}|||0|||2000|||1|||0||||||0|||200|||1|||2|||1|||1|||1|||0||||||0|||||||||||||||||||||1|||||||||300|||1||||||||||||||||||1|||";
$aStyle[14] = "yellow||||||yellow1|||".$myupload."|||550|||350|||rar|zip|pdf|doc|xls|ppt|chm|hlp|||swf|||gif|jpg|jpeg|bmp|png|||rm|flv|wmv|asf|mov|mpg|mpeg|avi|mp3|wav|mid|midi|ra|wma|||gif|jpg|bmp|png|||500|||100|||100|||100|||100|||1|||1|||EDIT|||1|||0||||||||||||1|||0|||V4.x版保留,standard550标配,yellow1皮肤|||1|||zh-cn|||0|||300|||120|||0|||版权所有...|||000000|||12|||宋体||||||0|||jpg|jpeg|||100|||FFFFFF|||1|||1|||gif|jpg|bmp|wmz|png|||100|||100|||1|||66|||17|||5|||5|||0|||100|||100|||1|||5|||5|||88|||31|||1|||0|||1|||1|||1|||1|||1|||0|||0|||0|||||||||1|||{page}|||0|||2000|||1|||0||||||0|||200|||1|||2|||1|||1|||1|||0||||||0|||||||||||||||||||||1|||||||||300|||1||||||||||||||||||1|||";
$aStyle[15] = "mini||||||office2003|||".$myupload."|||550|||350|||rar|zip|pdf|doc|xls|ppt|chm|hlp|||swf|||gif|jpg|jpeg|bmp|png|||rm|flv|wmv|asf|mov|mpg|mpeg|avi|mp3|wav|mid|midi|ra|wma|||gif|jpg|bmp|png|||500|||100|||100|||100|||100|||1|||1|||EDIT|||1|||0||||||||||||1|||0|||V4.x版保留,下拉框及菜单,全功能,占位小|||1|||zh-cn|||0|||300|||120|||0|||版权所有...|||FF0000|||12|||宋体||||||0|||jpg|jpeg|||100|||FFFFFF|||1|||1|||gif|jpg|bmp|wmz|png|||100|||100|||1|||73|||17|||5|||5|||0|||100|||100|||1|||5|||5|||88|||31|||1|||0|||1|||1|||1|||1|||1|||0|||0|||0|||||||||1|||{page}|||0|||2000|||1|||0||||||0|||200|||1|||2|||1|||1|||1|||0||||||0|||||||||||||||||||||1|||||||||300|||1||||||||||||||||||1|||";
$aStyle[16] = "popup||||||office2003|||".$myupload."|||550|||350|||rar|zip|pdf|doc|xls|ppt|chm|hlp|||swf|||gif|jpg|jpeg|bmp|png|||rm|flv|wmv|asf|mov|mpg|mpeg|avi|mp3|wav|mid|midi|ra|wma|||gif|jpg|bmp|png|||500|||100|||100|||100|||100|||1|||1|||EDIT|||1|||0||||||||||||1|||0|||V4.x版保留,standard550标配,office2003皮肤,弹窗模式调用|||1|||zh-cn|||0|||300|||120|||0|||版权所有...|||000000|||12|||宋体||||||0|||jpg|jpeg|||100|||FFFFFF|||1|||1|||gif|jpg|bmp|wmz|png|||100|||100|||1|||66|||17|||5|||5|||0|||100|||100|||1|||5|||5|||88|||31|||1|||0|||1|||1|||1|||1|||1|||0|||0|||0|||||||||1|||{page}|||0|||2000|||1|||0||||||0|||200|||1|||2|||1|||1|||1|||0||||||0|||||||||||||||||||||1|||||||||300|||1||||||||||||||||||1|||";
$aStyle[17] = "expand650||||||office2003|||".$myupload."|||650|||350|||rar|zip|pdf|doc|xls|ppt|chm|hlp|||swf|||gif|jpg|jpeg|bmp|png|||rm|flv|wmv|asf|mov|mpg|mpeg|avi|mp3|wav|mid|midi|ra|wma|||gif|jpg|bmp|png|||500|||100|||100|||100|||100|||1|||1|||EDIT|||1|||0||||||||||||1|||0|||650px宽度界面下的扩展工具栏按钮,默认只显示一行工具栏,点击扩展按钮,显示更多|||1|||zh-cn|||0|||300|||120|||0|||版权所有...|||000000|||12|||宋体||||||0|||jpg|jpeg|||100|||FFFFFF|||1|||1|||gif|jpg|bmp|wmz|png|||100|||100|||1|||73|||17|||5|||5|||0|||100|||100|||1|||5|||5|||88|||31|||1|||0|||1|||1|||1|||1|||1|||0|||0|||0|||||||||1|||{page}|||0|||2000|||1|||0||||||0|||200|||1|||2|||1|||1|||1|||0||||||0|||||||||||||||||||||1|||||||||300|||1||||||||||||||||||1|||";
$aStyle[18] = "expand600||||||office2003|||".$myupload."|||600|||350|||rar|zip|pdf|doc|xls|ppt|chm|hlp|||swf|||gif|jpg|jpeg|bmp|png|||rm|flv|wmv|asf|mov|mpg|mpeg|avi|mp3|wav|mid|midi|ra|wma|||gif|jpg|bmp|png|||500|||100|||100|||100|||100|||1|||1|||EDIT|||1|||0||||||||||||1|||0|||600px宽度界面下的标准工具栏按钮(推荐),默认只显示一行工具栏,点击扩展按钮,显示更多|||1|||zh-cn|||0|||300|||120|||0|||版权所有...|||000000|||12|||宋体||||||0|||jpg|jpeg|||100|||FFFFFF|||1|||1|||gif|jpg|bmp|wmz|png|||100|||100|||1|||66|||17|||5|||5|||0|||100|||100|||1|||5|||5|||88|||31|||1|||0|||1|||1|||1|||1|||1|||0|||0|||0|||||||||1|||{page}|||0|||2000|||1|||0||||||0|||200|||1|||2|||1|||1|||1|||0||||||0|||||||||||||||||||||1|||||||||300|||1||||||||||||||||||1|||";


$aToolbar[1] = "1|||TBHandle|FormatBlock|FontName|FontSize|Cut|Copy|Paste|PasteText|PasteWord|Delete|RemoveFormat|TBSep|FindReplace|SpellCheck|TBSep|UnDo|ReDo|TBSep|SelectAll|UnSelect|TBSep|absolutePosition|zIndexBackward|zIndexForward|||Toolbar1|||1";
$aToolbar[2] = "1|||TBHandle|Bold|Italic|UnderLine|StrikeThrough|SuperScript|SubScript|UpperCase|LowerCase|TBSep|JustifyLeft|JustifyCenter|JustifyRight|JustifyFull|TBSep|OrderedList|UnOrderedList|Indent|Outdent|TBSep|ForeColor|BackColor|TBSep|BgColor|BackImage|TBSep|Fieldset|Iframe|HorizontalRule|Marquee|TBSep|CreateLink|Anchor|Map|Unlink|||Toolbar2|||2";
$aToolbar[3] = "1|||TBHandle|Image|Flash|Media|File|GalleryMenu|TBSep|TableMenu|FormMenu|TBSep|RemoteUpload|LocalUpload|ImportWord|ImportExcel|Capture|TBSep|QuickFormat|ParagraphAttr|TBSep|Template|Symbol|Emot|Art|NowDate|NowTime|Excel|Quote|TBSep|PrintBreak|Print|TBSep|ShowBorders|ZoomMenu|Maximize|About|||Toolbar3|||3";
$aToolbar[4] = "2|||TBHandle|FormatBlock|FontName|FontSize|Cut|Copy|Paste|PasteText|PasteWord|TBSep|Delete|RemoveFormat|TBSep|FindReplace|TBSep|UnDo|ReDo|TBSep|SelectAll|UnSelect|TBSep|UpperCase|LowerCase|||工具栏1|||1";
$aToolbar[5] = "2|||TBHandle|Bold|Italic|UnderLine|StrikeThrough|SuperScript|SubScript|TBSep|JustifyLeft|JustifyCenter|JustifyRight|JustifyFull|ParagraphAttr|TBSep|OrderedList|UnOrderedList|Indent|Outdent|TBSep|ForeColor|BackColor|BgColor|BackImage|TBSep|Fieldset|HorizontalRule|Marquee|TBSep|CreateLink|Unlink|Map|Anchor|||工具栏2|||2";
$aToolbar[6] = "2|||TBHandle|Image|Flash|Media|File|GalleryMenu|TBSep|RemoteUpload|LocalUpload|ImportWord|ImportExcel|Capture|TBSep|TableMenu|FormMenu|TBSep|QuickFormat|TBSep|Template|Symbol|Emot|Art|Excel|PrintBreak|NowDate|NowTime|TBSep|Quote|ShowBorders|TBSep|ZoomMenu|Maximize|About|||工具栏3|||3";
$aToolbar[7] = "3|||TBHandle|FormatBlock|FontName|FontSize|Bold|Italic|UnderLine|StrikeThrough|TBSep|SuperScript|SubScript|UpperCase|LowerCase|TBSep|JustifyLeft|JustifyCenter|JustifyRight|JustifyFull|||工具栏1|||1";
$aToolbar[8] = "3|||TBHandle|Cut|Copy|Paste|PasteText|FindReplace|Delete|RemoveFormat|TBSep|UnDo|ReDo|SelectAll|UnSelect|TBSep|OrderedList|UnOrderedList|Indent|Outdent|ParagraphAttr|TBSep|ForeColor|BackColor|BgColor|BackImage|TBSep|RemoteUpload|LocalUpload|ImportWord|ImportExcel|||工具栏2|||2";
$aToolbar[9] = "3|||TBHandle|Image|Flash|Media|File|GalleryMenu|TBSep|TableMenu|QuickFormat|Capture|TBSep|Fieldset|HorizontalRule|Marquee|CreateLink|Unlink|Map|Anchor|TBSep|Template|Symbol|Emot|Art|Excel|Quote|ShowBorders|TBSep|Maximize|About|||工具栏3|||3";
$aToolbar[10] = "4|||TBHandle|FontNameMenu|FontSizeMenu|Bold|Italic|UnderLine|StrikeThrough|SuperScript|SubScript|UpperCase|LowerCase|TBSep|ForeColor|BackColor|BgColor|BackImage|TBSep|JustifyLeft|JustifyCenter|JustifyRight|JustifyFull|OrderedList|UnOrderedList|Indent|Outdent|||工具栏1|||1";
$aToolbar[11] = "4|||TBHandle|Cut|Copy|Paste|PasteText|PasteWord|FindReplace|Delete|RemoveFormat|QuickFormat|TBSep|UnDo|ReDo|SelectAll|UnSelect|TBSep|Fieldset|HorizontalRule|Marquee|CreateLink|Unlink|Map|Anchor|TBSep|ParagraphAttr|FormatBlockMenu|||工具栏2|||2";
$aToolbar[12] = "4|||TBHandle|Image|Flash|Media|File|GalleryMenu|RemoteUpload|LocalUpload|ImportWord|ImportExcel|Capture|TBSep|TableMenu|TBSep|Template|Symbol|Emot|Art|Excel|PrintBreak|Quote|ShowBorders|TBSep|ZoomMenu|Maximize|About|||工具栏3|||3";
$aToolbar[13] = "5|||TBHandle|FormatBlock|FontName|FontSize|Cut|Copy|Paste|PasteText|FindReplace|Delete|RemoveFormat|TBSep|FindReplace|SpellCheck|TBSep|UnDo|ReDo|TBSep|SelectAll|UnSelect|TBSep|absolutePosition|zIndexBackward|zIndexForward|||Toolbar1|||1";
$aToolbar[14] = "5|||TBHandle|Bold|Italic|UnderLine|StrikeThrough|SuperScript|SubScript|UpperCase|LowerCase|TBSep|JustifyLeft|JustifyCenter|JustifyRight|JustifyFull|TBSep|OrderedList|UnOrderedList|Indent|Outdent|TBSep|ForeColor|BackColor|TBSep|BgColor|BackImage|TBSep|Fieldset|Iframe|HorizontalRule|Marquee|TBSep|CreateLink|Anchor|Map|Unlink|||Toolbar2|||2";
$aToolbar[15] = "5|||TBHandle|Image|Flash|Media|File|GalleryMenu|TBSep|TableMenu|FormMenu|TBSep|RemoteUpload|LocalUpload|ImportWord|ImportExcel|TBSep|BR|Paragraph|ParagraphAttr|TBSep|Symbol|Emot|Art|NowDate|NowTime|Excel|Quote|TBSep|PrintBreak|Print|TBSep|ShowBorders|ZoomMenu|Refresh|Maximize|About|||Toolbar3|||3";
$aToolbar[16] = "5|||TBHandle|FontMenu|ParagraphMenu|ComponentMenu|ObjectMenu|ToolMenu|FileMenu|TBSep|TableMenu|TableInsert|TableProp|TableCellProp|TableCellSplit|TableRowProp|TableRowInsertAbove|TableRowInsertBelow|TableRowMerge|TableRowSplit|TableRowDelete|TableColInsertLeft|TableColInsertRight|TableColMerge|TableColSplit|TableColDelete|TBSep|FormMenu|FormText|FormTextArea|FormRadio|FormCheckbox|FormDropdown|FormButton|||Toolbar4|||4";
$aToolbar[17] = "5|||TBHandle|TBSep|GalleryMenu|GalleryImage|GalleryFlash|GalleryMedia|GalleryFile|TBSep|Code|EQ|TBSep|Big|Small|TBSep|ModeCode|ModeEdit|ModeText|ModeView|TBSep|SizePlus|SizeMinus|TBSep|ZoomSelect|TBSep|Template|QuickFormat|Capture|FontSizeMenu|FontNameMenu|FormatBlockMenu|TBSep|Pagination|PaginationInsert|TBSep|ShowBlocks|FormatBrush|Site|||Toolbar5|||5";
$aToolbar[18] = "6|||TBHandle|Cut|Copy|Paste|TBSep|FontSizeMenu|FontNameMenu|TBSep|Bold|Italic|UnderLine|TBSep|JustifyLeft|JustifyCenter|JustifyRight|TBSep|OrderedList|UnOrderedList|Indent|Outdent|TBSep|CreateLink|Unlink|TBSep|HorizontalRule|ForeColor|BackColor|TBSep|About|||工具栏1|||1";
$aToolbar[19] = "7|||TBHandle|FontNameMenu|FontSizeMenu|FormatBlockMenu|TBSep|EditMenu|FontMenu|ParagraphMenu|ComponentMenu|ObjectMenu|ToolMenu|FormMenu|TableMenu|FileMenu|GalleryMenu|TBSep|ZoomMenu|Maximize|About|||mini toolbar|||1";
$aToolbar[20] = "8|||TBHandle|FormatBlock|FontName|FontSize|Bold|Italic|UnderLine|StrikeThrough|TBSep|SuperScript|SubScript|UpperCase|LowerCase|TBSep|JustifyLeft|JustifyCenter|JustifyRight|JustifyFull|||工具栏1|||1";
$aToolbar[21] = "8|||TBHandle|Cut|Copy|Paste|PasteText|FindReplace|Delete|RemoveFormat|TBSep|UnDo|ReDo|SelectAll|UnSelect|TBSep|OrderedList|UnOrderedList|Indent|Outdent|ParagraphAttr|TBSep|ForeColor|BackColor|BgColor|BackImage|TBSep|RemoteUpload|LocalUpload|ImportWord|ImportExcel|||工具栏2|||2";
$aToolbar[22] = "8|||TBHandle|Image|Flash|Media|File|GalleryMenu|TBSep|TableMenu|QuickFormat|Capture|TBSep|Fieldset|HorizontalRule|Marquee|CreateLink|Unlink|Map|Anchor|TBSep|Template|Symbol|Emot|Art|Excel|Quote|ShowBorders|TBSep|Maximize|About|||工具栏3|||3";
$aToolbar[23] = "9|||TBHandle|FormatBlock|FontName|FontSize|Bold|Italic|UnderLine|StrikeThrough|TBSep|SuperScript|SubScript|UpperCase|LowerCase|TBSep|JustifyLeft|JustifyCenter|JustifyRight|JustifyFull|||工具栏1|||1";
$aToolbar[24] = "9|||TBHandle|Cut|Copy|Paste|PasteText|FindReplace|Delete|RemoveFormat|TBSep|UnDo|ReDo|SelectAll|UnSelect|TBSep|OrderedList|UnOrderedList|Indent|Outdent|ParagraphAttr|TBSep|ForeColor|BackColor|BgColor|BackImage|TBSep|RemoteUpload|LocalUpload|ImportWord|ImportExcel|||工具栏2|||2";
$aToolbar[25] = "9|||TBHandle|Image|Flash|Media|File|GalleryMenu|TBSep|TableMenu|QuickFormat|Capture|TBSep|Fieldset|HorizontalRule|Marquee|CreateLink|Unlink|Map|Anchor|TBSep|Template|Symbol|Emot|Art|Excel|Quote|ShowBorders|TBSep|Maximize|About|||工具栏3|||3";
$aToolbar[26] = "10|||TBHandle|FormatBlock|FontName|FontSize|Bold|Italic|UnderLine|StrikeThrough|TBSep|SuperScript|SubScript|UpperCase|LowerCase|TBSep|JustifyLeft|JustifyCenter|JustifyRight|JustifyFull|||工具栏1|||1";
$aToolbar[27] = "10|||TBHandle|Cut|Copy|Paste|PasteText|FindReplace|Delete|RemoveFormat|TBSep|UnDo|ReDo|SelectAll|UnSelect|TBSep|OrderedList|UnOrderedList|Indent|Outdent|ParagraphAttr|TBSep|ForeColor|BackColor|BgColor|BackImage|TBSep|RemoteUpload|LocalUpload|ImportWord|ImportExcel|||工具栏2|||2";
$aToolbar[28] = "10|||TBHandle|Image|Flash|Media|File|GalleryMenu|TBSep|TableMenu|QuickFormat|Capture|TBSep|Fieldset|HorizontalRule|Marquee|CreateLink|Unlink|Map|Anchor|TBSep|Template|Symbol|Emot|Art|Excel|Quote|ShowBorders|TBSep|Maximize|About|||工具栏3|||3";
$aToolbar[29] = "11|||TBHandle|FormatBlock|FontName|FontSize|Bold|Italic|UnderLine|StrikeThrough|TBSep|SuperScript|SubScript|UpperCase|LowerCase|TBSep|JustifyLeft|JustifyCenter|JustifyRight|JustifyFull|||工具栏1|||1";
$aToolbar[30] = "11|||TBHandle|Cut|Copy|Paste|PasteText|FindReplace|Delete|RemoveFormat|TBSep|UnDo|ReDo|SelectAll|UnSelect|TBSep|OrderedList|UnOrderedList|Indent|Outdent|ParagraphAttr|TBSep|ForeColor|BackColor|BgColor|BackImage|TBSep|RemoteUpload|LocalUpload|ImportWord|ImportExcel|||工具栏2|||2";
$aToolbar[31] = "11|||TBHandle|Image|Flash|Media|File|GalleryMenu|TBSep|TableMenu|QuickFormat|Capture|TBSep|Fieldset|HorizontalRule|Marquee|CreateLink|Unlink|Map|Anchor|TBSep|Template|Symbol|Emot|Art|Excel|Quote|ShowBorders|TBSep|Maximize|About|||工具栏3|||3";
$aToolbar[32] = "12|||TBHandle|FormatBlock|FontName|FontSize|Bold|Italic|UnderLine|StrikeThrough|TBSep|SuperScript|SubScript|UpperCase|LowerCase|TBSep|JustifyLeft|JustifyCenter|JustifyRight|JustifyFull|||工具栏1|||1";
$aToolbar[33] = "12|||TBHandle|Cut|Copy|Paste|PasteText|FindReplace|Delete|RemoveFormat|TBSep|UnDo|ReDo|SelectAll|UnSelect|TBSep|OrderedList|UnOrderedList|Indent|Outdent|ParagraphAttr|TBSep|ForeColor|BackColor|BgColor|BackImage|TBSep|RemoteUpload|LocalUpload|ImportWord|ImportExcel|||工具栏2|||2";
$aToolbar[34] = "12|||TBHandle|Image|Flash|Media|File|GalleryMenu|TBSep|TableMenu|QuickFormat|Capture|TBSep|Fieldset|HorizontalRule|Marquee|CreateLink|Unlink|Map|Anchor|TBSep|Template|Symbol|Emot|Art|Excel|Quote|ShowBorders|TBSep|Maximize|About|||工具栏3|||3";
$aToolbar[35] = "13|||TBHandle|FormatBlock|FontName|FontSize|Bold|Italic|UnderLine|StrikeThrough|TBSep|SuperScript|SubScript|UpperCase|LowerCase|TBSep|JustifyLeft|JustifyCenter|JustifyRight|JustifyFull|||工具栏1|||1";
$aToolbar[36] = "13|||TBHandle|Cut|Copy|Paste|PasteText|FindReplace|Delete|RemoveFormat|TBSep|UnDo|ReDo|SelectAll|UnSelect|TBSep|OrderedList|UnOrderedList|Indent|Outdent|ParagraphAttr|TBSep|ForeColor|BackColor|BgColor|BackImage|TBSep|RemoteUpload|LocalUpload|ImportWord|ImportExcel|||工具栏2|||2";
$aToolbar[37] = "13|||TBHandle|Image|Flash|Media|File|GalleryMenu|TBSep|TableMenu|QuickFormat|Capture|TBSep|Fieldset|HorizontalRule|Marquee|CreateLink|Unlink|Map|Anchor|TBSep|Template|Symbol|Emot|Art|Excel|Quote|ShowBorders|TBSep|Maximize|About|||工具栏3|||3";
$aToolbar[38] = "14|||TBHandle|FormatBlock|FontName|FontSize|Bold|Italic|UnderLine|StrikeThrough|TBSep|SuperScript|SubScript|UpperCase|LowerCase|TBSep|JustifyLeft|JustifyCenter|JustifyRight|JustifyFull|||工具栏1|||1";
$aToolbar[39] = "14|||TBHandle|Cut|Copy|Paste|PasteText|FindReplace|Delete|RemoveFormat|TBSep|UnDo|ReDo|SelectAll|UnSelect|TBSep|OrderedList|UnOrderedList|Indent|Outdent|ParagraphAttr|TBSep|ForeColor|BackColor|BgColor|BackImage|TBSep|RemoteUpload|LocalUpload|ImportWord|ImportExcel|||工具栏2|||2";
$aToolbar[40] = "14|||TBHandle|Image|Flash|Media|File|GalleryMenu|TBSep|TableMenu|QuickFormat|Capture|TBSep|Fieldset|HorizontalRule|Marquee|CreateLink|Unlink|Map|Anchor|TBSep|Template|Symbol|Emot|Art|Excel|Quote|ShowBorders|TBSep|Maximize|About|||工具栏3|||3";
$aToolbar[41] = "15|||TBHandle|FontName|FontSize|TBSep|EditMenu|FontMenu|ParagraphMenu|ComponentMenu|ObjectMenu|ToolMenu|FormMenu|TableMenu|FileMenu|GalleryMenu|FormatBlockMenu|ZoomMenu|TBSep|Maximize|About|||mini toolbar|||1";
$aToolbar[42] = "16|||TBHandle|FormatBlock|FontName|FontSize|Bold|Italic|UnderLine|StrikeThrough|TBSep|SuperScript|SubScript|UpperCase|LowerCase|TBSep|JustifyLeft|JustifyCenter|JustifyRight|JustifyFull|||工具栏1|||1";
$aToolbar[43] = "16|||TBHandle|Cut|Copy|Paste|PasteText|FindReplace|Delete|RemoveFormat|TBSep|UnDo|ReDo|SelectAll|UnSelect|TBSep|OrderedList|UnOrderedList|Indent|Outdent|ParagraphAttr|TBSep|ForeColor|BackColor|BgColor|BackImage|TBSep|RemoteUpload|LocalUpload|ImportWord|ImportExcel|||工具栏2|||2";
$aToolbar[44] = "16|||TBHandle|Image|Flash|Media|File|GalleryMenu|TBSep|TableMenu|QuickFormat|Capture|TBSep|Fieldset|HorizontalRule|Marquee|CreateLink|Unlink|Map|Anchor|TBSep|Template|Symbol|Emot|Art|Excel|Quote|ShowBorders|TBSep|Save|About|||工具栏3|||3";
$aToolbar[45] = "17|||TBHandle|FontName|FontSize|Cut|Copy|Paste|PasteText|FormatBrush|TBSep|Bold|Italic|UnderLine|StrikeThrough|TBSep|JustifyLeft|JustifyCenter|JustifyRight|JustifyFull|TBSep|OrderedList|UnOrderedList|Indent|Outdent|TBSep|ForeColor|BackColor|TBSep|Maximize|ExpandToolbar|||Toolbar1|||1";
$aToolbar[46] = "17|||TBHandle|UnDo|ReDo|TBSep|FormatBlockMenu|ParagraphAttr|TBSep|PasteWord|SuperScript|SubScript|UpperCase|LowerCase|Delete|RemoveFormat|TBSep|SelectAll|UnSelect|TBSep|FindReplace|SpellCheck|TBSep|BgColor|BackImage|TBSep|Fieldset|Iframe|HorizontalRule|Marquee|TBSep|CreateLink|Anchor|Map|Unlink|TBSep|absolutePosition|zIndexBackward|zIndexForward|||Toolbar2|||2";
$aToolbar[47] = "17|||TBHandle|Image|Flash|Media|File|GalleryMenu|TBSep|TableMenu|FormMenu|TBSep|RemoteUpload|LocalUpload|ImportWord|ImportExcel|ImportPPT|Capture|TBSep|QuickFormat|TBSep|Template|Symbol|Emot|Art|NowDate|NowTime|Excel|Quote|TBSep|PrintBreak|Print|TBSep|ShowBorders|ShowBlocks|ZoomMenu|About|||Toolbar3|||3";
$aToolbar[48] = "18|||TBHandle|FontName|FontSize|Cut|Copy|Paste|PasteText|PasteWord|FormatBrush|TBSep|Bold|Italic|UnderLine|StrikeThrough|TBSep|JustifyLeft|JustifyCenter|JustifyRight|JustifyFull|TBSep|ForeColor|BackColor|TBSep|Maximize|ExpandToolbar|||工具栏1|||1";
$aToolbar[49] = "18|||TBHandle|UnDo|ReDo|TBSep|FormatBlockMenu|ParagraphAttr|TBSep|OrderedList|UnOrderedList|Indent|Outdent|TBSep|SuperScript|SubScript|TBSep|Delete|RemoveFormat|TBSep|SelectAll|UnSelect|TBSep|FindReplace|SpellCheck|TBSep|BgColor|BackImage|TBSep|Fieldset|HorizontalRule|Marquee|TBSep|CreateLink|Unlink|Map|Anchor|||工具栏2|||2";
$aToolbar[50] = "18|||TBHandle|Image|Flash|Media|File|GalleryMenu|TBSep|RemoteUpload|LocalUpload|ImportWord|ImportExcel|Capture|TBSep|TableMenu|FormMenu|TBSep|QuickFormat|TBSep|Template|Symbol|Emot|Art|Excel|PrintBreak|NowDate|NowTime|TBSep|Quote|ShowBorders|ShowBlocks|ZoomMenu|About|||工具栏3|||3";

?>